//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template_4333
{
    using System;
    using System.Collections.Generic;
    
    public partial class isrpo
    {
        public string ID { get; set; }
        public string НаименованиеУслуги { get; set; }
        public string ВидУслуги { get; set; }
        public string КодУслуги { get; set; }
        public string Стоимость { get; set; }
    }
}
